### PR TITLE
Use NPM to source fav.js dependency

### PR DESCRIPTION
**Pull request by jamesb93**
This PR makes it such that fav.js is now sourced from the @flucoma/fav repository on npm (rather than a bunch of local files).

As such the build process was changed slightly and the repo was cleaned up of files which can be gathered from `pnpm install`.

- remove superfluous files
- update package.json to use new @flucoma./fav
- ignore pnpm locks
- update fav-max compile
- update build instructions in readme.md

### CODE REVIEW

**Review by weefuzzy — COMMENTED** [review]
I don't think this quite does what I do at the build stage, but it's a bit hard to tell.

**Review by weefuzzy — APPROVED** [review]
Ok, those commits sort out the building I think 
* paths needed updating for rollup to combine my files with Fav.js ones
* there was one change I'd had to make by hand to Fav because Max js doesn't know about `Float32Array`, this is now done as part of the bundling.

Ready to go, I think, conflicts notwithstanding

**Comment by weefuzzy** [comment]
Although: if you're now running an action to do the bundling, can take the compiled js out of source control? It's just causing conflicts every time

**Comment by weefuzzy** [comment]
Ah, ffs. Something else has broken now 😭

**Comment by jamesb93** [comment]
> Although: if you're now running an action to do the bundling, can take the compiled js out of source control? It's just causing conflicts every time

For sure. What can I help with apart from that?

**Comment by weefuzzy** [comment]
Think this works now. Small crimes involved

**Comment by jamesb93** [comment]
> Think this works now. Small crimes involved

🚔 take him away toys

**Pull request merged**
