### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by jamesb93**
This fixes two issues that were present in fluid.waveform~

1. If no `buffer` was passed to the waveform~ view then the background wouldn't draw because `disp === null`. I've made a cheap fix to this although its not great and might actually harm performance? I don't understand the code well enough.

2. I added a filter to check if an empty or bogus buffer has been passed to fluid.waveform~ which was causing also sorts of redness.

### CODE REVIEW

**Comment by weefuzzy** [comment]
I'll need to look more closely, but my memory is that we do check for buffer validity, but later. The case for doing it later is that in certain circumstances a buffer might not exist *yet* when this is called (e.g. from a `loadbang`), but will do shortly. So, as with the C++, the habit has been to defer checking until the moment that data is actually needed.

I guess a separate question is to do with how much squawking should happen when a buffer isn't valid.

**Comment by weefuzzy** [comment]
I think we only need a much simpler change – suggested updated pushed to this PR

**Comment by jamesb93** [comment]
I like it. Thanks for taking a gander.

**Comment by jamesb93** [comment]
Okay gander taken, is this works so I assume ready to merge?

**Pull request merged**
